language: node_js
node_js:
  - 'stable'

branches:
  only:
    - feature/ci-cd

env:
  global:
    - CC_TEST_REPORTER_ID=0f594ecd1c19874759be811508bfc0c3ff0f78d3b432adefd355e9e56ce67110
cache:
  directories:
    - node_modules

before_install:
  - nvm install 13
  - node --version
  - openssl aes-256-cbc -K $encrypted_1a6dcd56cf03_key -iv $encrypted_1a6dcd56cf03_iv -in android/app/gds-upload-keystore.jks.enc -out android/app/gds-upload-keystore.jks -d

install:
  - npm install
  - yes | sdkmanager "platforms;android-28"
  - touch .env
  - echo "API_URL=http://gds.proepi.org.br" > .env
  - echo "APP_ID=1" >> .env

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

      
android:
  components:
    - build-tools-29.0.3
    - android-29
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
    - addon-google_apis-google-16

jobs:
  include:
    - stage: 'Test'
      script:
        - npm run test --coverage
      script: skip
    - stage: 'Deploy'
      provider: releases
      skip_cleanup: 'true'
      script: bash deploy.sh
      api_key:
        secure: xWfNCAJ+520sFClvY879VXWXiPS5O7sJDBMkd25jyk6Va0ogjM3VklGBnQzkhsULcR9v15loIIGmfbBQhabw81csfuoBWDkLqC36wPqNTiSqRPTmNfo741MoWsmNE/x1s46LGe6qLphTyNPTn7GbBm05bixOZjYwy3NtM6a4CiUo+OwmlY0R6Ow0jN23Sm5EY5OYXDp4f/M0SS+5pnSTx651TTfJpZJ6BLbQk9PQrlmhB7hQDUcrDPGvrXu57QisHaib8DYkJtrNI57pDmShB2WaP1B6QKkWzIUqBq/L3CvGBrOEvBTv+7XPd23RIqWux4qFZX3NfVeo34vHbeJw9s7vCbFmRk1IiSa2/0MRJn9d5X5pZ9ftJfXbkCR4G/pFBvr3m4zqXnR+zk/u4a++nBv/E2iNbMPajUfNCOYfQlj8jKZLrxuyv24DpRleql4CZHZRtO8lA8dXhreN+1HMcpFr6+kdR0MyIlROmO0z1y6Z3tP0i8ylpUi+BlvbvDG9HIzML8vZ4V9YhXUly0311f32NEByH/5VrqWN7t1boJbnQDwfDT2aAh2gaQ70C2/PRMcukSKL36GCCOS7TAOPz7gc5XX0W4g82GSdrZmYHuwAxlB+ltXCzEe89K+e23qIgLudi9x5twxuMpmgkmIqgkOZHe9VB3cRWCABq5VtjL8=
        file: app-release.apk
      on:
        repo: proepidesenvolvimento/guardioes-app
        branch: 
          - master
          - feature/ci-cd

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov coverage/lcov.info
